#' Create a track from an R data frame for a custom JBrowse 2 view
#'
#' Creates the necessary configuration string for an R
#' data frame so that it can be viewed as a track in a
#' JBrowse custom linear genome view.
#'
#' @param track_data the data frame (must have cols: chrom, start, end, id)
#' @param assembly the config string generated by \code{assembly}
#'
#' @return a character vector of stringified track JSON configuration
#'
#' @export
#'
#' @examples
#' assembly <- assembly("https://jbrowse.org/genomes/hg19/fasta/hg19.fa.gz", bgzip = TRUE)
#'
#'
track_data_frame <- function(track_data, assembly) {
  check_df(track_data)


}

check_df <- function(track_data) {
  if (!is.data.frame(track_data)) {
    stop("track data must be a data frame.")
  }
  if (invalid_cols(track_data)) {
   stop("data frame must contain columns: chrom, start, end, id.")
  }
}

invalid_cols <- function(df) {
  columns_present <- is.element(c("chrom", "start", "end", "id"), colnames(df))
  is.element(FALSE, columns_present)
}
